//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextKey() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGame.TextKey", typeof(TextKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backToMap.
        /// </summary>
        public static string backToMap {
            get {
                return ResourceManager.GetString("backToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyGame.
        /// </summary>
        public static string BuyGame {
            get {
                return ResourceManager.GetString("BuyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continueGame.
        /// </summary>
        public static string continueGame {
            get {
                return ResourceManager.GetString("continueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditsDesc.
        /// </summary>
        public static string CreditsDesc {
            get {
                return ResourceManager.GetString("CreditsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBossMacedoniaIntro1.
        /// </summary>
        public static string DialogBossMacedoniaIntro1 {
            get {
                return ResourceManager.GetString("DialogBossMacedoniaIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBossMacedoniaIntro2.
        /// </summary>
        public static string DialogBossMacedoniaIntro2 {
            get {
                return ResourceManager.GetString("DialogBossMacedoniaIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBossMacedoniaOutro1.
        /// </summary>
        public static string DialogBossMacedoniaOutro1 {
            get {
                return ResourceManager.GetString("DialogBossMacedoniaOutro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBossMacedoniaOutro2.
        /// </summary>
        public static string DialogBossMacedoniaOutro2 {
            get {
                return ResourceManager.GetString("DialogBossMacedoniaOutro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBossMacedoniaOutro3.
        /// </summary>
        public static string DialogBossMacedoniaOutro3 {
            get {
                return ResourceManager.GetString("DialogBossMacedoniaOutro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish1.
        /// </summary>
        public static string DialogDarkWish1 {
            get {
                return ResourceManager.GetString("DialogDarkWish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish2.
        /// </summary>
        public static string DialogDarkWish2 {
            get {
                return ResourceManager.GetString("DialogDarkWish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish3.
        /// </summary>
        public static string DialogDarkWish3 {
            get {
                return ResourceManager.GetString("DialogDarkWish3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish4.
        /// </summary>
        public static string DialogDarkWish4 {
            get {
                return ResourceManager.GetString("DialogDarkWish4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish5.
        /// </summary>
        public static string DialogDarkWish5 {
            get {
                return ResourceManager.GetString("DialogDarkWish5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish6.
        /// </summary>
        public static string DialogDarkWish6 {
            get {
                return ResourceManager.GetString("DialogDarkWish6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish7.
        /// </summary>
        public static string DialogDarkWish7 {
            get {
                return ResourceManager.GetString("DialogDarkWish7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWish8.
        /// </summary>
        public static string DialogDarkWish8 {
            get {
                return ResourceManager.GetString("DialogDarkWish8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWishRemind1.
        /// </summary>
        public static string DialogDarkWishRemind1 {
            get {
                return ResourceManager.GetString("DialogDarkWishRemind1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogDarkWishRemind2.
        /// </summary>
        public static string DialogDarkWishRemind2 {
            get {
                return ResourceManager.GetString("DialogDarkWishRemind2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticBad1.
        /// </summary>
        public static string DialogEpilepticBad1 {
            get {
                return ResourceManager.GetString("DialogEpilepticBad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticBad2.
        /// </summary>
        public static string DialogEpilepticBad2 {
            get {
                return ResourceManager.GetString("DialogEpilepticBad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticBad3.
        /// </summary>
        public static string DialogEpilepticBad3 {
            get {
                return ResourceManager.GetString("DialogEpilepticBad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticBadSpecial.
        /// </summary>
        public static string DialogEpilepticBadSpecial {
            get {
                return ResourceManager.GetString("DialogEpilepticBadSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticGood1.
        /// </summary>
        public static string DialogEpilepticGood1 {
            get {
                return ResourceManager.GetString("DialogEpilepticGood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticGood2.
        /// </summary>
        public static string DialogEpilepticGood2 {
            get {
                return ResourceManager.GetString("DialogEpilepticGood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticGoodSpecial.
        /// </summary>
        public static string DialogEpilepticGoodSpecial {
            get {
                return ResourceManager.GetString("DialogEpilepticGoodSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticIntro1.
        /// </summary>
        public static string DialogEpilepticIntro1 {
            get {
                return ResourceManager.GetString("DialogEpilepticIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticIntro2.
        /// </summary>
        public static string DialogEpilepticIntro2 {
            get {
                return ResourceManager.GetString("DialogEpilepticIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticMedium1.
        /// </summary>
        public static string DialogEpilepticMedium1 {
            get {
                return ResourceManager.GetString("DialogEpilepticMedium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticMedium2.
        /// </summary>
        public static string DialogEpilepticMedium2 {
            get {
                return ResourceManager.GetString("DialogEpilepticMedium2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticMedium3.
        /// </summary>
        public static string DialogEpilepticMedium3 {
            get {
                return ResourceManager.GetString("DialogEpilepticMedium3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogEpilepticMediumSpecial.
        /// </summary>
        public static string DialogEpilepticMediumSpecial {
            get {
                return ResourceManager.GetString("DialogEpilepticMediumSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogLearnDash.
        /// </summary>
        public static string DialogLearnDash {
            get {
                return ResourceManager.GetString("DialogLearnDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogOnionIntro1.
        /// </summary>
        public static string DialogOnionIntro1 {
            get {
                return ResourceManager.GetString("DialogOnionIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogOnionIntro2.
        /// </summary>
        public static string DialogOnionIntro2 {
            get {
                return ResourceManager.GetString("DialogOnionIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogOnionIntro3.
        /// </summary>
        public static string DialogOnionIntro3 {
            get {
                return ResourceManager.GetString("DialogOnionIntro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogOnionIntro4.
        /// </summary>
        public static string DialogOnionIntro4 {
            get {
                return ResourceManager.GetString("DialogOnionIntro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogOnionIntro5.
        /// </summary>
        public static string DialogOnionIntro5 {
            get {
                return ResourceManager.GetString("DialogOnionIntro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogOnionIntro6.
        /// </summary>
        public static string DialogOnionIntro6 {
            get {
                return ResourceManager.GetString("DialogOnionIntro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogTomatoAttack1.
        /// </summary>
        public static string DialogTomatoAttack1 {
            get {
                return ResourceManager.GetString("DialogTomatoAttack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogTomatoComes1.
        /// </summary>
        public static string DialogTomatoComes1 {
            get {
                return ResourceManager.GetString("DialogTomatoComes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogTomatoComes2.
        /// </summary>
        public static string DialogTomatoComes2 {
            get {
                return ResourceManager.GetString("DialogTomatoComes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogTomatoComes3.
        /// </summary>
        public static string DialogTomatoComes3 {
            get {
                return ResourceManager.GetString("DialogTomatoComes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitDesc.
        /// </summary>
        public static string ExitDesc {
            get {
                return ResourceManager.GetString("ExitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamePaused.
        /// </summary>
        public static string gamePaused {
            get {
                return ResourceManager.GetString("gamePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageNewSkills.
        /// </summary>
        public static string MessageNewSkills {
            get {
                return ResourceManager.GetString("MessageNewSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewGame.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewGameDesc.
        /// </summary>
        public static string NewGameDesc {
            get {
                return ResourceManager.GetString("NewGameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptBack.
        /// </summary>
        public static string OptBack {
            get {
                return ResourceManager.GetString("OptBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptBackDesc.
        /// </summary>
        public static string OptBackDesc {
            get {
                return ResourceManager.GetString("OptBackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionsDesc.
        /// </summary>
        public static string OptionsDesc {
            get {
                return ResourceManager.GetString("OptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptMusicVol.
        /// </summary>
        public static string OptMusicVol {
            get {
                return ResourceManager.GetString("OptMusicVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptMusicVolDesc.
        /// </summary>
        public static string OptMusicVolDesc {
            get {
                return ResourceManager.GetString("OptMusicVolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptNo.
        /// </summary>
        public static string OptNo {
            get {
                return ResourceManager.GetString("OptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptNoDesc.
        /// </summary>
        public static string OptNoDesc {
            get {
                return ResourceManager.GetString("OptNoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptRumble.
        /// </summary>
        public static string OptRumble {
            get {
                return ResourceManager.GetString("OptRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptRumbleDesc.
        /// </summary>
        public static string OptRumbleDesc {
            get {
                return ResourceManager.GetString("OptRumbleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptSoundVol.
        /// </summary>
        public static string OptSoundVol {
            get {
                return ResourceManager.GetString("OptSoundVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptSoundVolDesc.
        /// </summary>
        public static string OptSoundVolDesc {
            get {
                return ResourceManager.GetString("OptSoundVolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptYes.
        /// </summary>
        public static string OptYes {
            get {
                return ResourceManager.GetString("OptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptYesDesc.
        /// </summary>
        public static string OptYesDesc {
            get {
                return ResourceManager.GetString("OptYesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressAenterLevel.
        /// </summary>
        public static string pressAenterLevel {
            get {
                return ResourceManager.GetString("pressAenterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PressAToStart.
        /// </summary>
        public static string PressAToStart {
            get {
                return ResourceManager.GetString("PressAToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressBACKskillsMenu.
        /// </summary>
        public static string pressBACKskillsMenu {
            get {
                return ResourceManager.GetString("pressBACKskillsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressBBack.
        /// </summary>
        public static string pressBBack {
            get {
                return ResourceManager.GetString("pressBBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressBBackMenu.
        /// </summary>
        public static string pressBBackMenu {
            get {
                return ResourceManager.GetString("pressBBackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressBBackToGame.
        /// </summary>
        public static string pressBBackToGame {
            get {
                return ResourceManager.GetString("pressBBackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PressBToMenu.
        /// </summary>
        public static string PressBToMenu {
            get {
                return ResourceManager.GetString("PressBToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressLSselectLevel.
        /// </summary>
        public static string pressLSselectLevel {
            get {
                return ResourceManager.GetString("pressLSselectLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PressStartToCont.
        /// </summary>
        public static string PressStartToCont {
            get {
                return ResourceManager.GetString("PressStartToCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoresDesc.
        /// </summary>
        public static string ScoresDesc {
            get {
                return ResourceManager.GetString("ScoresDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skillDash.
        /// </summary>
        public static string skillDash {
            get {
                return ResourceManager.GetString("skillDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skillLife.
        /// </summary>
        public static string skillLife {
            get {
                return ResourceManager.GetString("skillLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skillPlasma.
        /// </summary>
        public static string skillPlasma {
            get {
                return ResourceManager.GetString("skillPlasma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skillPowerShot.
        /// </summary>
        public static string skillPowerShot {
            get {
                return ResourceManager.GetString("skillPowerShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
