//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextKey() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGame.TextKey", typeof(TextKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyGame.
        /// </summary>
        internal static string BuyGame {
            get {
                return ResourceManager.GetString("BuyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditsDesc.
        /// </summary>
        internal static string CreditsDesc {
            get {
                return ResourceManager.GetString("CreditsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitDesc.
        /// </summary>
        internal static string ExitDesc {
            get {
                return ResourceManager.GetString("ExitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewGame.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewGameDesc.
        /// </summary>
        internal static string NewGameDesc {
            get {
                return ResourceManager.GetString("NewGameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptBack.
        /// </summary>
        internal static string OptBack {
            get {
                return ResourceManager.GetString("OptBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptBackDesc.
        /// </summary>
        internal static string OptBackDesc {
            get {
                return ResourceManager.GetString("OptBackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionsDesc.
        /// </summary>
        internal static string OptionsDesc {
            get {
                return ResourceManager.GetString("OptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptMusicVol.
        /// </summary>
        internal static string OptMusicVol {
            get {
                return ResourceManager.GetString("OptMusicVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptMusicVolDesc.
        /// </summary>
        internal static string OptMusicVolDesc {
            get {
                return ResourceManager.GetString("OptMusicVolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptNo.
        /// </summary>
        internal static string OptNo {
            get {
                return ResourceManager.GetString("OptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptNoDesc.
        /// </summary>
        internal static string OptNoDesc {
            get {
                return ResourceManager.GetString("OptNoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptRumble.
        /// </summary>
        internal static string OptRumble {
            get {
                return ResourceManager.GetString("OptRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptRumbleDesc.
        /// </summary>
        internal static string OptRumbleDesc {
            get {
                return ResourceManager.GetString("OptRumbleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptSoundVol.
        /// </summary>
        internal static string OptSoundVol {
            get {
                return ResourceManager.GetString("OptSoundVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptSoundVolDesc.
        /// </summary>
        internal static string OptSoundVolDesc {
            get {
                return ResourceManager.GetString("OptSoundVolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptYes.
        /// </summary>
        internal static string OptYes {
            get {
                return ResourceManager.GetString("OptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptYesDesc.
        /// </summary>
        internal static string OptYesDesc {
            get {
                return ResourceManager.GetString("OptYesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PressAToStart.
        /// </summary>
        internal static string PressAToStart {
            get {
                return ResourceManager.GetString("PressAToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PressBToMenu.
        /// </summary>
        internal static string PressBToMenu {
            get {
                return ResourceManager.GetString("PressBToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PressStartToCont.
        /// </summary>
        internal static string PressStartToCont {
            get {
                return ResourceManager.GetString("PressStartToCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        internal static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoresDesc.
        /// </summary>
        internal static string ScoresDesc {
            get {
                return ResourceManager.GetString("ScoresDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
